"""同步数据库

Revision ID: 03f87de7dcbb
Revises: 34fb55825233
Create Date: 2026-04-19 20:28:27.575503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03f87de7dcbb'
down_revision: Union[str, Sequence[str], None] = '34fb55825233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_path', sa.String(length=500), nullable=False, comment='MD文件存储的物理路径'))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'))
        batch_op.alter_column('html_content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(),
               nullable=True,
               comment='可选：缓存的HTML渲染内容',
               existing_comment='渲染HTML')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.LONGTEXT(), nullable=False, comment='源码'))
        batch_op.alter_column('html_content',
               existing_type=sa.Text(),
               type_=mysql.LONGTEXT(),
               nullable=False,
               comment='渲染HTML',
               existing_comment='可选：缓存的HTML渲染内容')
        batch_op.drop_column('published_at')
        batch_op.drop_column('content_path')

    # ### end Alembic commands ###
