"""同步1

Revision ID: e13722da1ae2
Revises: 03f87de7dcbb
Create Date: 2026-04-21 15:02:57.548538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e13722da1ae2'
down_revision: Union[str, Sequence[str], None] = '03f87de7dcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_audited', sa.Boolean(), server_default='0', nullable=False, comment='是否已审核'))
        batch_op.alter_column('content_path',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               comment='Markdown文件物理路径',
               existing_comment='MD文件存储的物理路径',
               existing_nullable=False)
        batch_op.alter_column('cover_image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='文章封面图',
               existing_nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=mysql.DATETIME(),
               comment='软删除时间',
               existing_comment='删除时间（软删除）',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_article_status'))
        batch_op.drop_index(batch_op.f('ix_article_view_count'))
        batch_op.create_index(batch_op.f('ix_article_is_audited'), ['is_audited'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_article_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_article_user_id_user'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('html_content')
        batch_op.drop_column('editor_type')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父级ID',
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment=None,
               existing_comment='内容',
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               comment=None,
               existing_comment='昵称',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
        batch_op.alter_column('is_audited',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='审核状态',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父评论ID',
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('reply_content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment=None,
               existing_comment='博主回复',
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像路径'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='激活状态'))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='加密哈希密码',
               existing_comment='哈希密码',
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'COMMON', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='用户角色',
               existing_comment='角色',
               existing_nullable=False,
               existing_server_default=sa.text("'COMMON'"))
        batch_op.alter_column('login_attempts',
               existing_type=mysql.INTEGER(),
               comment='失败尝试次数',
               existing_comment='失败次数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('last_fail_time',
               existing_type=mysql.DATETIME(),
               comment='上次失败时间',
               existing_comment='最后失败时间',
               existing_nullable=True)

    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='邮箱地址',
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='验证码',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='过期时间',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('deleted_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='删除时间（软删除）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_codes', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=mysql.DATETIME(),
               comment='删除时间（软删除）',
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('expires_at',
               existing_type=mysql.DATETIME(),
               comment='过期时间',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=10),
               comment='验证码',
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               comment='邮箱地址',
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_fail_time',
               existing_type=mysql.DATETIME(),
               comment='最后失败时间',
               existing_comment='上次失败时间',
               existing_nullable=True)
        batch_op.alter_column('login_attempts',
               existing_type=mysql.INTEGER(),
               comment='失败次数',
               existing_comment='失败尝试次数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'COMMON', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='角色',
               existing_comment='用户角色',
               existing_nullable=False,
               existing_server_default=sa.text("'COMMON'"))
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment='哈希密码',
               existing_comment='加密哈希密码',
               existing_nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('avatar')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('reply_content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='博主回复',
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment='父评论ID',
               existing_nullable=True)
        batch_op.alter_column('is_audited',
               existing_type=mysql.TINYINT(display_width=1),
               comment='审核状态',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               comment='邮箱',
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               comment='昵称',
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               comment='内容',
               existing_nullable=False)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=mysql.INTEGER(),
               comment='父级ID',
               existing_nullable=True)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editor_type', mysql.ENUM('MARKDOWN', 'RICHTEXT', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'), server_default=sa.text("'MARKDOWN'"), nullable=False, comment='编辑器类型'))
        batch_op.add_column(sa.Column('html_content', mysql.TEXT(), nullable=True, comment='可选：缓存的HTML渲染内容'))
        batch_op.drop_constraint(batch_op.f('fk_article_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_article_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_article_is_audited'))
        batch_op.create_index(batch_op.f('ix_article_view_count'), ['view_count'], unique=False)
        batch_op.create_index(batch_op.f('ix_article_status'), ['status'], unique=False)
        batch_op.alter_column('deleted_at',
               existing_type=mysql.DATETIME(),
               comment='删除时间（软删除）',
               existing_comment='软删除时间',
               existing_nullable=True)
        batch_op.alter_column('cover_image',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               comment=None,
               existing_comment='文章封面图',
               existing_nullable=True)
        batch_op.alter_column('content_path',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               comment='MD文件存储的物理路径',
               existing_comment='Markdown文件物理路径',
               existing_nullable=False)
        batch_op.drop_column('is_audited')

    # ### end Alembic commands ###
